name: Deploy Flask App to Vercel

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Install Vercel CLI
      run: |
        npm install -g vercel  # Install Vercel CLI globally

    - name: Deploy to Vercel
      run: |
        vercel --prod --yes  # Deploy to Vercel in production mode automatically
      env:
        VERCEL_TOKEN: 'SIIaBBWlbINhZQWKuOdGfQcx'  # Use the token directly for deployment
